### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by JonasL0430** [Cyber2049/Epic-Fight---Indestructible#11]
Is it possible you could add a way to change the scale of the player as well? Given that you can change the scale of any other entity, I'm hoping it shouldn't be too complicated

**Comment by Cyber2049** [comment]
use pehkui

**Comment by JonasL0430** [comment]
Pehkui doesn't work. It scales the player model but not the weapon colliders. So if the player is scaled to be large, you still only do damage as if the player is swinging a tiny weapon low to the ground.
