### ISSUE TITLE
20.8.1 Datapack crash

### ISSUE THREAD

**Issue by Illest8** [Cyber2049/Epic-Fight---Indestructible#14]
Upon updating EpicFight, WoM, and Indestructible to the latest versions, my previously working indestructible datapack is crashing my game. Here is the issue:

https://pastebin.com/bhchS9Bk

**Comment by Illest8** [comment]
If I remove the datapack folder, the mod itself does not crash the game.

**Comment by Cyber2049** [comment]
the format of predicate is wrong. {"predicate":"indestructible:guard_break", "invert": true}
