### ISSUE TITLE
Crash Report for 1.18.2

### ISSUE THREAD

**Issue by InteJason** [Cyber2049/Epic-Fight---Indestructible#2]
Crash Report: https://mclo.gs/OQQt0Qi
Log: https://mclo.gs/Bd3dcRI

This happened in dev environment.

**Comment by Cyber2049** [comment]
> Crash Report: https://mclo.gs/OQQt0Qi Log: https://mclo.gs/Bd3dcRI
> 
> This happened in dev environment.

Strange, only AdvancedHAdvancedCustomimHumanoidMobPatch can use Guard AI. Any ​detailed information

**Comment by InteJason** [comment]
Please tell me what details you need. This crash happened once randomly. Here is the only entity that uses the guard ai in my test environment: https://mclo.gs/RzOYTUl

**Comment by SettingDust** [comment]
It's related to `simple_mobs:samurai_5` in the crash report (Dawncraft Mobs).

**Comment by Cyber2049** [comment]
I tested your datapack. It works normally.
