### ISSUE TITLE
No chase animations/motions 1.18.2

### ISSUE THREAD

**Issue by qVoidreaver** [Cyber2049/Epic-Fight---Indestructible#7]
The "chase" animations are being ignored. Only the "walk" animations are being applied. 

Latest version 1.18.2 (18.5.7)

**Comment by Cyber2049** [comment]
See. Will fix in next update.

**Comment by AzureAxi** [comment]
> The "chase" animations are being ignored. Only the "walk" animations are being applied.
> 
> Latest version 1.18.2 (18.5.7)

I do not understand, how do i make the chase animations not be ignored?
